# Change these first
owner: locaal-ai # Your GitHub organization or username, where this repository lives
repo: statuspage # The name of this repository

sites:
  - name: Contents Pal Website
    url: https://www.contentspal.com
  - name: Contents Pal Application
    url: https://app.contentspal.com

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /statuspage
  logoUrl: https://drive.google.com/u/0/drive-viewer/AKGpihZzySBn2EAUYYGEqNa_ItVaGiEx5YjYrwCsEvrTFyx7kbUsc4steMQQT1TJmNhkbWUqKBJ8me64Ca1vXPYxDKGXHqnCrDV7b38=s2560
  name: Locaal AI / Contents Pal
  introTitle: "Contents Pal - the leading AI contents claims processing platform"
  introMessage: [Contents Pal](https://contentspal.com) helps your teams create fast and accurate content inventories and valuation reports using simple apps and AI agents.
  publish: true
  navbar:
    - title: Status
      href: /
    - title: Contents Pal
      href: https://contentspal.com

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
